/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WohnmobileIndexRouteImport } from './routes/wohnmobile.index'
import { Route as WohnmobileNeuRouteImport } from './routes/wohnmobile.neu'
import { Route as FahrzeugeNeuRouteImport } from './routes/fahrzeuge.neu'
import { Route as WohnmobileIdIndexRouteImport } from './routes/wohnmobile.$id.index'
import { Route as FahrzeugeIdIndexRouteImport } from './routes/fahrzeuge.$id.index'
import { Route as WohnmobileIdBearbeitenRouteImport } from './routes/wohnmobile.$id.bearbeiten'
import { Route as FahrzeugeIdBearbeitenRouteImport } from './routes/fahrzeuge.$id.bearbeiten'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WohnmobileIndexRoute = WohnmobileIndexRouteImport.update({
  id: '/wohnmobile/',
  path: '/wohnmobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const WohnmobileNeuRoute = WohnmobileNeuRouteImport.update({
  id: '/wohnmobile/neu',
  path: '/wohnmobile/neu',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrzeugeNeuRoute = FahrzeugeNeuRouteImport.update({
  id: '/fahrzeuge/neu',
  path: '/fahrzeuge/neu',
  getParentRoute: () => rootRouteImport,
} as any)
const WohnmobileIdIndexRoute = WohnmobileIdIndexRouteImport.update({
  id: '/wohnmobile/$id/',
  path: '/wohnmobile/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrzeugeIdIndexRoute = FahrzeugeIdIndexRouteImport.update({
  id: '/fahrzeuge/$id/',
  path: '/fahrzeuge/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WohnmobileIdBearbeitenRoute = WohnmobileIdBearbeitenRouteImport.update({
  id: '/wohnmobile/$id/bearbeiten',
  path: '/wohnmobile/$id/bearbeiten',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrzeugeIdBearbeitenRoute = FahrzeugeIdBearbeitenRouteImport.update({
  id: '/fahrzeuge/$id/bearbeiten',
  path: '/fahrzeuge/$id/bearbeiten',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/login': typeof LoginRoute
  '/fahrzeuge/neu': typeof FahrzeugeNeuRoute
  '/wohnmobile/neu': typeof WohnmobileNeuRoute
  '/wohnmobile/': typeof WohnmobileIndexRoute
  '/fahrzeuge/$id/bearbeiten': typeof FahrzeugeIdBearbeitenRoute
  '/wohnmobile/$id/bearbeiten': typeof WohnmobileIdBearbeitenRoute
  '/fahrzeuge/$id/': typeof FahrzeugeIdIndexRoute
  '/wohnmobile/$id/': typeof WohnmobileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/login': typeof LoginRoute
  '/fahrzeuge/neu': typeof FahrzeugeNeuRoute
  '/wohnmobile/neu': typeof WohnmobileNeuRoute
  '/wohnmobile': typeof WohnmobileIndexRoute
  '/fahrzeuge/$id/bearbeiten': typeof FahrzeugeIdBearbeitenRoute
  '/wohnmobile/$id/bearbeiten': typeof WohnmobileIdBearbeitenRoute
  '/fahrzeuge/$id': typeof FahrzeugeIdIndexRoute
  '/wohnmobile/$id': typeof WohnmobileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/login': typeof LoginRoute
  '/fahrzeuge/neu': typeof FahrzeugeNeuRoute
  '/wohnmobile/neu': typeof WohnmobileNeuRoute
  '/wohnmobile/': typeof WohnmobileIndexRoute
  '/fahrzeuge/$id/bearbeiten': typeof FahrzeugeIdBearbeitenRoute
  '/wohnmobile/$id/bearbeiten': typeof WohnmobileIdBearbeitenRoute
  '/fahrzeuge/$id/': typeof FahrzeugeIdIndexRoute
  '/wohnmobile/$id/': typeof WohnmobileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/einstellungen'
    | '/login'
    | '/fahrzeuge/neu'
    | '/wohnmobile/neu'
    | '/wohnmobile/'
    | '/fahrzeuge/$id/bearbeiten'
    | '/wohnmobile/$id/bearbeiten'
    | '/fahrzeuge/$id/'
    | '/wohnmobile/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/einstellungen'
    | '/login'
    | '/fahrzeuge/neu'
    | '/wohnmobile/neu'
    | '/wohnmobile'
    | '/fahrzeuge/$id/bearbeiten'
    | '/wohnmobile/$id/bearbeiten'
    | '/fahrzeuge/$id'
    | '/wohnmobile/$id'
  id:
    | '__root__'
    | '/'
    | '/einstellungen'
    | '/login'
    | '/fahrzeuge/neu'
    | '/wohnmobile/neu'
    | '/wohnmobile/'
    | '/fahrzeuge/$id/bearbeiten'
    | '/wohnmobile/$id/bearbeiten'
    | '/fahrzeuge/$id/'
    | '/wohnmobile/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinstellungenRoute: typeof EinstellungenRoute
  LoginRoute: typeof LoginRoute
  FahrzeugeNeuRoute: typeof FahrzeugeNeuRoute
  WohnmobileNeuRoute: typeof WohnmobileNeuRoute
  WohnmobileIndexRoute: typeof WohnmobileIndexRoute
  FahrzeugeIdBearbeitenRoute: typeof FahrzeugeIdBearbeitenRoute
  WohnmobileIdBearbeitenRoute: typeof WohnmobileIdBearbeitenRoute
  FahrzeugeIdIndexRoute: typeof FahrzeugeIdIndexRoute
  WohnmobileIdIndexRoute: typeof WohnmobileIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wohnmobile/': {
      id: '/wohnmobile/'
      path: '/wohnmobile'
      fullPath: '/wohnmobile/'
      preLoaderRoute: typeof WohnmobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wohnmobile/neu': {
      id: '/wohnmobile/neu'
      path: '/wohnmobile/neu'
      fullPath: '/wohnmobile/neu'
      preLoaderRoute: typeof WohnmobileNeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrzeuge/neu': {
      id: '/fahrzeuge/neu'
      path: '/fahrzeuge/neu'
      fullPath: '/fahrzeuge/neu'
      preLoaderRoute: typeof FahrzeugeNeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wohnmobile/$id/': {
      id: '/wohnmobile/$id/'
      path: '/wohnmobile/$id'
      fullPath: '/wohnmobile/$id/'
      preLoaderRoute: typeof WohnmobileIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrzeuge/$id/': {
      id: '/fahrzeuge/$id/'
      path: '/fahrzeuge/$id'
      fullPath: '/fahrzeuge/$id/'
      preLoaderRoute: typeof FahrzeugeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wohnmobile/$id/bearbeiten': {
      id: '/wohnmobile/$id/bearbeiten'
      path: '/wohnmobile/$id/bearbeiten'
      fullPath: '/wohnmobile/$id/bearbeiten'
      preLoaderRoute: typeof WohnmobileIdBearbeitenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrzeuge/$id/bearbeiten': {
      id: '/fahrzeuge/$id/bearbeiten'
      path: '/fahrzeuge/$id/bearbeiten'
      fullPath: '/fahrzeuge/$id/bearbeiten'
      preLoaderRoute: typeof FahrzeugeIdBearbeitenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinstellungenRoute: EinstellungenRoute,
  LoginRoute: LoginRoute,
  FahrzeugeNeuRoute: FahrzeugeNeuRoute,
  WohnmobileNeuRoute: WohnmobileNeuRoute,
  WohnmobileIndexRoute: WohnmobileIndexRoute,
  FahrzeugeIdBearbeitenRoute: FahrzeugeIdBearbeitenRoute,
  WohnmobileIdBearbeitenRoute: WohnmobileIdBearbeitenRoute,
  FahrzeugeIdIndexRoute: FahrzeugeIdIndexRoute,
  WohnmobileIdIndexRoute: WohnmobileIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
